version: '3.8'

services:
    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - 5000:5000
        volumes:
            - ./frontend:/app:Z
        restart: always

    postgres:
        container_name: postgres
        restart: always
        image: postgres:14
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        env_file:
            - ./.env.db

    redis:
        container_name: redis
        image: redis:5
        restart: unless-stopped
        ports:
            - 6379:6379

    wsgiserver:
        build:            
            context: ./backend
            dockerfile: Dockerfile
        container_name: wsgiserver
        restart: always
        command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 
        env_file:
            - ./.env
        volumes:
            - static_volume:/usr/src/app/staticfiles/
            - media_volume:/usr/src/app/media/
        links:
            - postgres
            - redis
        expose:
            - 8000

    asgiserver:
        build:            
            context: ./backend
            dockerfile: Dockerfile
        container_name: asgiserver
        restart: always
        command: daphne core.asgi:application -b 0.0.0.0 -p 9000
        env_file:
            - ./.env
        links:
            - postgres
            - redis
        expose:
            - 9000


volumes:
    static_volume: 
    media_volume:
    postgres_data:
    frontend:
