# Generated by Django 3.2.11 on 2022-06-10 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Medecin'), (2, 'Accueil'), (3, 'Assistant'), (4, 'Admin')], null=True)),
                ('master_role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Medecin'), (2, 'Accueil'), (3, 'Assistant'), (4, 'Admin')], null=True)),
                ('pin', models.CharField(blank=True, max_length=4, null=True)),
                ('theme', models.CharField(choices=[('light', 'light')], default='light', max_length=6)),
                ('box', models.TextField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
