# Generated by Django 3.2.11 on 2022-07-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.TextField(blank=True, null=True)),
                ('center_html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.center'),
        ),
    ]
