# Generated by Django 3.2.11 on 2022-07-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220719_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='centre',
            new_name='center',
        ),
    ]
