# Generated by Django 3.2.11 on 2022-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_centre_profile_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rpps_identifier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialty_code',
            field=models.CharField(blank=True, default='5', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
