# Generated by Django 3.2.11 on 2022-07-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220719_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='postal_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
